### ISSUE TITLE
Some items not available through API?

### ISSUE THREAD

**Issue by fabstu** [hoenn/go-hn#3]
Hi! I'm currently trying out the library and it works very well, thanks for your this! I came upon an issue with the HackerNews API, which somebody may also have encountered. For a certain comment item, there is no entry in firebase:

- https://hacker-news.firebaseio.com/v0/item/29082464.json
- https://news.ycombinator.com/item?id=29082464

Is this only happening to me or also to somebody else? Before this comment arrived, my small script was able to recursively retrieve all items beginning at the root of the discussion:

- https://news.ycombinator.com/item?id=29068652

**Comment by hoenn** [comment]
Hey @fabstu :wave:  
I can reproduce this in the browser which leads me to think this must be on the hackernews side and unrelated to this library. 

I really have no idea why that would be the case and doesn't appear to be an issue for other comments that user has made, I suggest shooting an email to `hn@ycombinator.com` and they might be able to tell us some more. 

I'll close the issue for now, but if you learn anything that could be a workaround I'd be happy to add it to the library or review a PR.
